In [643]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
plt.rc("font", size=14)
%matplotlib inline

# 1.HEPATITIS

In [644]:
df = pd.read_csv('HEPATITIS_TRAIN.csv')
df.head()

age  sex  steroid  antivirals  ...  albumin  protime  histology  Class
0   28    1        1           2  ...     4.00       46          1      0
1   47    2        2           2  ...     2.60       31          2      1
2   38    1        1           1  ...     4.20       62          1      0
3   32    1        2           2  ...     4.00       90          1      0
4   44    1        1           2  ...     3.81       41          2      1

[5 rows x 20 columns]

In [645]:
df.shape

(113, 20)

In [646]:
test_data = pd.read_csv('HEPATITIS_TEST.csv')
test_data.head()

age  sex  steroid  antivirals  ...  albumin  protime  histology  Class
0   51    1        2           2  ...      3.0       63          2      0
1   57    1        2           2  ...      2.6       73          1      1
2   44    1        1           2  ...      3.5       61          2      0
3   57    1        1           2  ...      3.3       30          2      1
4   45    1        2           1  ...      4.2       85          2      0

[5 rows x 20 columns]

In [647]:
test_data.shape

(29, 20)

In [648]:
X_train = df.drop('Class',axis=1)
Y_train = df['Class']
X_test = test_data.drop('Class', axis=1)
Y_test = test_data['Class']

# LOGISTIC REGRESSION

In [649]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
logreg = LogisticRegression()
logreg.fit(X_train,Y_train)
predicted = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test,Y_test)))

Accuracy of logistic regression classifier on test set: 0.86


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [650]:
report = classification_report(Y_test, predicted)
print(report)


              precision    recall  f1-score   support

           0       0.96      0.88      0.92        25
           1       0.50      0.75      0.60         4

    accuracy                           0.86        29
   macro avg       0.73      0.81      0.76        29
weighted avg       0.89      0.86      0.87        29



In [651]:
ans=confusion_matrix(Y_test,predicted)
ans

array([[22,  3],
       [ 1,  3]])

In [652]:
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
specificity

0.88

In [653]:
 hamming_loss = metrics.hamming_loss(Y_test, predicted)
 hamming_loss 

0.13793103448275862

In [654]:
# Entropy loss
#where 0 denotes perfect classification or zero impurity.
cross_entropy_loss = metrics.log_loss(Y_test, predicted)
cross_entropy_loss 

4.764051874894252

# DECISION TREE

In [655]:
from sklearn.tree import DecisionTreeClassifier
DTClassifier= DecisionTreeClassifier(criterion='entropy', random_state=1)
DTClassifier.fit(X_train,Y_train)
print('Accuracy of logistic decision tree classifier on test set: {:.2f}'.format(DTClassifier.score(X_test, Y_test)))

Accuracy of logistic decision tree classifier on test set: 0.79


In [656]:
predicted = DTClassifier.predict(X_test)
report = classification_report(Y_test, predicted)
print(report)


              precision    recall  f1-score   support

           0       0.95      0.80      0.87        25
           1       0.38      0.75      0.50         4

    accuracy                           0.79        29
   macro avg       0.66      0.78      0.68        29
weighted avg       0.87      0.79      0.82        29



In [657]:
ans=metrics.confusion_matrix(Y_test,predicted)
ans

array([[20,  5],
       [ 1,  3]])

In [658]:
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
specificity

0.8

In [659]:
 hamming_loss = metrics.hamming_loss(Y_test, predicted)
 hamming_loss 

0.20689655172413793

In [660]:
cross_entropy_loss = metrics.log_loss(Y_test, predicted)
cross_entropy_loss 

7.146091598503968

# 3.GAUSSIAN NAIVE BAYES

In [661]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train,Y_train)
print('Accuracy of naive bayes classifier on test set: {:.2f}'.format(model.score(X_test, Y_test)))
predicted = model.predict(X_test)
report = classification_report(Y_test, predicted)
print(report)

Accuracy of naive bayes classifier on test set: 0.83
              precision    recall  f1-score   support

           0       0.95      0.84      0.89        25
           1       0.43      0.75      0.55         4

    accuracy                           0.83        29
   macro avg       0.69      0.79      0.72        29
weighted avg       0.88      0.83      0.85        29



In [662]:
ans=confusion_matrix(Y_test,predicted)
ans

array([[21,  4],
       [ 1,  3]])

In [663]:
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
specificity

0.84

In [664]:
hamming_loss = metrics.hamming_loss(Y_test, predicted)
hamming_loss 

0.1724137931034483

In [665]:
cross_entropy_loss = metrics.log_loss(Y_test, predicted)
cross_entropy_loss 

5.95507173669911

# 4.SVM

In [666]:
from sklearn.svm import SVC

svcclassifier = SVC(kernel='sigmoid')
svcclassifier.fit(X_train,Y_train)
print('Accuracy of SVM classifier on test set: : {:.2f}'.format(svcclassifier.score(X_test,Y_test)))

Accuracy of SVM classifier on test set: : 0.86


In [667]:
predicted = svcclassifier.predict(X_test)

report = classification_report(Y_test, predicted)
print(report)

              precision    recall  f1-score   support

           0       0.86      1.00      0.93        25
           1       0.00      0.00      0.00         4

    accuracy                           0.86        29
   macro avg       0.43      0.50      0.46        29
weighted avg       0.74      0.86      0.80        29



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [668]:
ans=confusion_matrix(Y_test,predicted)
ans

array([[25,  0],
       [ 4,  0]])

In [669]:
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
specificity

1.0

In [670]:
hamming_loss = metrics.hamming_loss(Y_test, predicted)
hamming_loss 

0.13793103448275862

In [671]:
cross_entropy_loss = metrics.log_loss(Y_test, predicted)
cross_entropy_loss 

4.763969157918715

# 5.NEURAL NETWORK

In [672]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)
clf.fit(X_train, Y_train)
print('Accuracy of MLP classifier on test set: : {:.2f}'.format(clf.score(X_test,Y_test)))

Accuracy of MLP classifier on test set: : 0.76


In [673]:
predicted = clf.predict(X_test)

report = classification_report(Y_test, predicted)
print(report)

              precision    recall  f1-score   support

           0       0.85      0.88      0.86        25
           1       0.00      0.00      0.00         4

    accuracy                           0.76        29
   macro avg       0.42      0.44      0.43        29
weighted avg       0.73      0.76      0.74        29



In [674]:
ans=confusion_matrix(Y_test,predicted)
ans

array([[22,  3],
       [ 4,  0]])

In [675]:
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
specificity

0.88

In [676]:
hamming_loss = metrics.hamming_loss(Y_test, predicted)
hamming_loss 

0.2413793103448276

In [677]:
Cross_entropy_loss = metrics.log_loss(Y_test, predicted)
cross_entropy_loss 

4.763969157918715

# 6.RANDOM FOREST

In [678]:
from sklearn.ensemble import RandomForestClassifier

RFC = RandomForestClassifier(n_estimators=10)
RFC = RFC.fit(X_train, Y_train)
print('Accuracy of Random Forest classifier on test set: : {:.2f}'.format(RFC.score(X_test,Y_test)))

Accuracy of Random Forest classifier on test set: : 0.86


In [679]:
predicted = RFC.predict(X_test)

report = classification_report(Y_test, predicted)
print(report)

              precision    recall  f1-score   support

           0       0.92      0.92      0.92        25
           1       0.50      0.50      0.50         4

    accuracy                           0.86        29
   macro avg       0.71      0.71      0.71        29
weighted avg       0.86      0.86      0.86        29



In [680]:
ans=confusion_matrix(Y_test,predicted)
ans

array([[23,  2],
       [ 2,  2]])

In [681]:
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
specificity

0.92

In [682]:
hamming_loss = metrics.hamming_loss(Y_test, predicted)
hamming_loss 

0.13793103448275862

In [683]:
Cross_entropy_loss = metrics.log_loss(Y_test, predicted)
cross_entropy_loss 

4.763969157918715

# 7.LINEAR MODEL

In [684]:
from sklearn.linear_model import SGDClassifier

clf = SGDClassifier(loss="hinge", penalty="l2", max_iter=5)
clf.fit(X_train, Y_train)
print('Accuracy of Random Forest classifier on test set: : {:.2f}'.format(clf.score(X_test,Y_test)))

Accuracy of Random Forest classifier on test set: : 0.83


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


In [685]:
predicted = clf.predict(X_test)
report = classification_report(Y_test, predicted)
print(report)

              precision    recall  f1-score   support

           0       0.86      0.96      0.91        25
           1       0.00      0.00      0.00         4

    accuracy                           0.83        29
   macro avg       0.43      0.48      0.45        29
weighted avg       0.74      0.83      0.78        29



In [686]:
ans=confusion_matrix(Y_test,predicted)
ans

array([[24,  1],
       [ 4,  0]])

In [687]:
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
specificity

0.96

In [688]:
hamming_loss = metrics.hamming_loss(Y_test, predicted)
hamming_loss 

0.1724137931034483

In [689]:
Cross_entropy_loss = metrics.log_loss(Y_test, predicted)
cross_entropy_loss 

4.763969157918715

# BREAST DATASET

In [690]:
df = pd.read_csv('BREAST_TRAIN.csv')
df.head()

radius_2ean  texture_2ean  ...  fractal_di2ension_worst  Class
0        13.48         20.82  ...                  0.10710      0
1        14.99         22.11  ...                  0.09251      1
2        12.21         14.09  ...                  0.08824      1
3        16.26         21.88  ...                  0.07953      0
4        20.31         27.06  ...                  0.07999      0

[5 rows x 31 columns]

In [691]:
test_data = pd.read_csv('BREAST_TEST.csv')
test_data.head()

radius_2ean  texture_2ean  ...  fractal_di2ension_worst  Class
0        8.597         18.60  ...                  0.08116      1
1       12.680         23.84  ...                  0.10310      0
2       19.210         18.57  ...                  0.08294      0
3        9.606         16.84  ...                  0.09825      1
4       16.690         20.20  ...                  0.07623      0

[5 rows x 31 columns]

In [692]:
df.shape


(455, 31)

In [693]:
rows,columns=test_data.shape
columns

31

In [694]:
X = df.drop('Class',axis=1)
Y = df['Class']
res = test_data['Class']
test_data = test_data.drop('Class', axis=1)

LOGISTIC REGRESSION

In [695]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X, Y)
predicted = logreg.predict(test_data)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(test_data, res)))

Accuracy of logistic regression classifier on test set: 0.95


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [696]:
report = classification_report(res, predicted)
print(report)


              precision    recall  f1-score   support

           0       0.93      0.93      0.93        40
           1       0.96      0.96      0.96        74

    accuracy                           0.95       114
   macro avg       0.94      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114



In [697]:
ans=confusion_matrix(res,predicted)
ans

array([[37,  3],
       [ 3, 71]])

In [698]:
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
specificity

0.925

In [699]:
hamming_loss = metrics.hamming_loss(res, predicted)
hamming_loss 

0.05263157894736842

In [700]:
Cross_entropy_loss = metrics.log_loss(res, predicted)
cross_entropy_loss 

4.763969157918715

DECISION TREE


In [701]:
from sklearn.tree import DecisionTreeClassifier
DTClassifier= DecisionTreeClassifier(criterion='entropy', random_state=1)
DTClassifier.fit(X,Y)
print('Accuracy of logistic decision tree classifier on test set: {:.2f}'.format(DTClassifier.score(test_data, res)))

Accuracy of logistic decision tree classifier on test set: 0.95


In [702]:
predicted = DTClassifier.predict(test_data)
report = classification_report(res, predicted)
print(report)


              precision    recall  f1-score   support

           0       0.90      0.95      0.93        40
           1       0.97      0.95      0.96        74

    accuracy                           0.95       114
   macro avg       0.94      0.95      0.94       114
weighted avg       0.95      0.95      0.95       114



In [703]:
ans=confusion_matrix(res,predicted)
ans

array([[38,  2],
       [ 4, 70]])

In [704]:
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
specificity

0.95

In [705]:
hamming_loss = metrics.hamming_loss(res, predicted)
hamming_loss 

0.05263157894736842

In [706]:
Cross_entropy_loss = metrics.log_loss(res, predicted)
cross_entropy_loss 

4.763969157918715

NAIVE BAYES

In [707]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X,Y)
print('Accuracy of naive bayes classifier on test set: {:.2f}'.format(model.score(test_data, res)))
predicted = model.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of naive bayes classifier on test set: 0.94
              precision    recall  f1-score   support

           0       0.95      0.88      0.91        40
           1       0.94      0.97      0.95        74

    accuracy                           0.94       114
   macro avg       0.94      0.92      0.93       114
weighted avg       0.94      0.94      0.94       114



In [708]:
ans=confusion_matrix(res,predicted)
ans

array([[35,  5],
       [ 2, 72]])

In [709]:
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
specificity

0.875

In [710]:
hamming_loss = metrics.hamming_loss(res, predicted)
hamming_loss 

0.06140350877192982

In [711]:
Cross_entropy_loss = metrics.log_loss(res, predicted)
cross_entropy_loss 

4.763969157918715

SVM

In [712]:
from sklearn.svm import SVC

svcclassifier = SVC(kernel='sigmoid')
svcclassifier.fit(X,Y)
print('Accuracy of SVM classifier on test set: : {:.2f}'.format(svcclassifier.score(test_data,res)))
predicted = svcclassifier.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of SVM classifier on test set: : 0.44
              precision    recall  f1-score   support

           0       0.17      0.15      0.16        40
           1       0.56      0.59      0.58        74

    accuracy                           0.44       114
   macro avg       0.37      0.37      0.37       114
weighted avg       0.42      0.44      0.43       114



In [713]:
ans=confusion_matrix(res,predicted)
ans

array([[ 6, 34],
       [30, 44]])

In [714]:
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
specificity

0.15

In [715]:
hamming_loss = metrics.hamming_loss(res, predicted)
hamming_loss 

0.5614035087719298

In [716]:
Cross_entropy_loss = metrics.log_loss(res, predicted)
cross_entropy_loss 

4.763969157918715

NEURAL NETWORK

In [717]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)
clf.fit(X, Y)
print('Accuracy of MLP classifier on test set: : {:.2f}'.format(clf.score(test_data,res)))
predicted = clf.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of MLP classifier on test set: : 0.35
              precision    recall  f1-score   support

           0       0.35      1.00      0.52        40
           1       0.00      0.00      0.00        74

    accuracy                           0.35       114
   macro avg       0.18      0.50      0.26       114
weighted avg       0.12      0.35      0.18       114



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [718]:
ans=confusion_matrix(res,predicted)
ans

array([[40,  0],
       [74,  0]])

In [719]:
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
specificity

1.0

In [720]:
hamming_loss = metrics.hamming_loss(res, predicted)
hamming_loss 

0.6491228070175439

In [721]:
Cross_entropy_loss = metrics.log_loss(res, predicted)
cross_entropy_loss 

4.763969157918715

RANDOM FOREST

In [722]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=10)
clf = clf.fit(X, Y)
print('Accuracy of Random Forest classifier on test set: : {:.2f}'.format(clf.score(test_data,res)))
predicted = clf.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of Random Forest classifier on test set: : 0.98
              precision    recall  f1-score   support

           0       0.95      1.00      0.98        40
           1       1.00      0.97      0.99        74

    accuracy                           0.98       114
   macro avg       0.98      0.99      0.98       114
weighted avg       0.98      0.98      0.98       114



In [723]:
ans=confusion_matrix(res,predicted)
ans

array([[40,  0],
       [ 2, 72]])

In [724]:
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
specificity

1.0

In [725]:
hamming_loss = metrics.hamming_loss(res, predicted)
hamming_loss 

0.017543859649122806

In [726]:
Cross_entropy_loss = metrics.log_loss(res, predicted)
cross_entropy_loss 

4.763969157918715

LINEAR MODEL

In [727]:
from sklearn.linear_model import SGDClassifier

clf = SGDClassifier(loss="hinge", penalty="l2", max_iter=5)
clf.fit(X, Y)
print('Accuracy of Random Forest classifier on test set: : {:.2f}'.format(clf.score(test_data,res)))
predicted = clf.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of Random Forest classifier on test set: : 0.88


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


              precision    recall  f1-score   support

           0       0.96      0.68      0.79        40
           1       0.85      0.99      0.91        74

    accuracy                           0.88       114
   macro avg       0.91      0.83      0.85       114
weighted avg       0.89      0.88      0.87       114



In [728]:
ans=confusion_matrix(res,predicted)
ans

array([[27, 13],
       [ 1, 73]])

In [729]:
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
specificity

0.675

In [730]:
hamming_loss = metrics.hamming_loss(res, predicted)
hamming_loss 

0.12280701754385964

In [731]:
cross_entropy_loss = metrics.log_loss(res, predicted)
cross_entropy_loss 

4.2416953008363345

# HEART DATA SET

In [732]:
df = pd.read_csv('HEART_TRAIN.csv')
df.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  Class
0   41    0   1       105   198    0  ...      0      0.0      2   1     2      1
1   64    1   0       120   246    0  ...      1      2.2      0   1     2      0
2   62    0   0       124   209    0  ...      0      0.0      2   0     2      1
3   45    0   1       112   160    0  ...      0      0.0      1   0     2      1
4   39    0   2        94   199    0  ...      0      0.0      2   0     2      1

[5 rows x 14 columns]

In [733]:
test_data = pd.read_csv('HEART_TEST.csv')
test_data.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  Class
0   59    1   0       164   176    1  ...      0      1.0      1   2     1      0
1   58    1   0       150   270    0  ...      1      0.8      2   0     3      0
2   52    1   1       134   201    0  ...      0      0.8      2   1     2      1
3   58    1   0       125   300    0  ...      0      0.0      2   2     3      0
4   65    1   0       110   248    0  ...      0      0.6      2   2     1      0

[5 rows x 14 columns]

In [734]:
X = df.drop('Class',axis=1)
Y = df['Class']
res = test_data['Class']
test_data = test_data.drop('Class', axis=1)

LOGISTIC REGRESSION

In [735]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X, Y)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(test_data, res)))
predicted =logreg.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of logistic regression classifier on test set: 0.80
              precision    recall  f1-score   support

           0       1.00      0.65      0.79        34
           1       0.69      1.00      0.82        27

    accuracy                           0.80        61
   macro avg       0.85      0.82      0.80        61
weighted avg       0.86      0.80      0.80        61



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [736]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 


[[22 12]
 [ 0 27]]
0.6470588235294118
0.19672131147540983
6.794670687017879


DECISION TREE

In [737]:
from sklearn.tree import DecisionTreeClassifier
DTClassifier= DecisionTreeClassifier(criterion='entropy', random_state=2)
DTClassifier.fit(X,Y)
print('Accuracy of logistic decision tree classifier on test set: {:.2f}'.format(DTClassifier.score(test_data, res)))
predicted = DTClassifier.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of logistic decision tree classifier on test set: 0.74
              precision    recall  f1-score   support

           0       0.85      0.65      0.73        34
           1       0.66      0.85      0.74        27

    accuracy                           0.74        61
   macro avg       0.75      0.75      0.74        61
weighted avg       0.76      0.74      0.74        61



In [738]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 


[[22 12]
 [ 4 23]]
0.6470588235294118
0.26229508196721313
9.059508483405464


NAIVE BAYES

In [739]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X,Y)
print('Accuracy of naive bayes classifier on test set: {:.2f}'.format(model.score(test_data, res)))
predicted = model.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of naive bayes classifier on test set: 0.87
              precision    recall  f1-score   support

           0       1.00      0.76      0.87        34
           1       0.77      1.00      0.87        27

    accuracy                           0.87        61
   macro avg       0.89      0.88      0.87        61
weighted avg       0.90      0.87      0.87        61



In [740]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 


[[26  8]
 [ 0 27]]
0.7647058823529411
0.13114754098360656
4.52978045801192


SVC

In [741]:
from sklearn.svm import SVC

svcclassifier = SVC(kernel='sigmoid')
svcclassifier.fit(X,Y)
print('Accuracy of SVM classifier on test set: : {:.2f}'.format(svcclassifier.score(test_data,res)))
predicted = svcclassifier.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of SVM classifier on test set: : 0.44
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        34
           1       0.44      1.00      0.61        27

    accuracy                           0.44        61
   macro avg       0.22      0.50      0.31        61
weighted avg       0.20      0.44      0.27        61



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [742]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 



[[ 0 34]
 [ 0 27]]
0.0
0.5573770491803278
19.251566946550646


NEURAL NETWORK

In [743]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)
clf.fit(X, Y)
print('Accuracy of MLP classifier on test set: : {:.2f}'.format(clf.score(test_data,res)))
predicted = clf.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of MLP classifier on test set: : 0.56
              precision    recall  f1-score   support

           0       0.56      1.00      0.72        34
           1       0.00      0.00      0.00        27

    accuracy                           0.56        61
   macro avg       0.28      0.50      0.36        61
weighted avg       0.31      0.56      0.40        61



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [744]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 



[[34  0]
 [27  0]]
1.0
0.4426229508196721
15.287655125616203


RANDOM FOREST

In [745]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=10)
clf = clf.fit(X, Y)
print('Accuracy of Random Forest classifier on test set: : {:.2f}'.format(clf.score(test_data,res)))
predicted = clf.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of Random Forest classifier on test set: : 0.77
              precision    recall  f1-score   support

           0       0.88      0.68      0.77        34
           1       0.69      0.89      0.77        27

    accuracy                           0.77        61
   macro avg       0.79      0.78      0.77        61
weighted avg       0.80      0.77      0.77        61



In [746]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 



[[23 11]
 [ 3 24]]
0.6764705882352942
0.22950819672131148
7.927076477057077


LINEAR MODEL

In [747]:
from sklearn.linear_model import SGDClassifier

clf = SGDClassifier(loss="hinge", penalty="l2", max_iter=5)
clf.fit(X, Y)
print('Accuracy of Random Forest classifier on test set: : {:.2f}'.format(clf.score(test_data,res)))
predicted = clf.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of Random Forest classifier on test set: : 0.56


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


              precision    recall  f1-score   support

           0       0.89      0.24      0.37        34
           1       0.50      0.96      0.66        27

    accuracy                           0.56        61
   macro avg       0.69      0.60      0.52        61
weighted avg       0.72      0.56      0.50        61



In [748]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 



[[ 8 26]
 [ 1 26]]
0.23529411764705882
0.4426229508196721
15.287995937635634


# **PIMA** **DATA** **SET**

In [749]:
df = pd.read_csv('PIMA_TRAIN.csv')
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Class
0            2      129             74  ...                     0.591   25      0
1            9      184             85  ...                     1.213   49      1
2            7      150             66  ...                     0.718   42      0
3            2       89             90  ...                     0.292   42      0
4           14      100             78  ...                     0.412   46      1

[5 rows x 9 columns]

In [750]:
test_data = pd.read_csv('PIMA_TEST.csv')
test_data.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Class
0            3       96             56  ...                     0.944   39      0
1            7      106             92  ...                     0.235   48      0
2            7      194             68  ...                     0.745   41      1
3            0       95             80  ...                     0.330   26      0
4            3      102             44  ...                     0.400   26      0

[5 rows x 9 columns]

In [751]:
X = df.drop('Class',axis=1)
Y = df['Class']
res = test_data['Class']
test_data = test_data.drop('Class', axis=1)

LOGISTIC REGRESSION

In [752]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X, Y)
predicted =logreg.predict(test_data)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(test_data, res)))
report = classification_report(res, predicted)
print(report)

Accuracy of logistic regression classifier on test set: 0.82
              precision    recall  f1-score   support

           0       0.82      0.93      0.87       103
           1       0.81      0.59      0.68        51

    accuracy                           0.82       154
   macro avg       0.82      0.76      0.78       154
weighted avg       0.82      0.82      0.81       154



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [753]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 



[[96  7]
 [21 30]]
0.9320388349514563
0.18181818181818182
6.279813871685134


DECISION TREE

In [754]:
from sklearn.tree import DecisionTreeClassifier
DTClassifier= DecisionTreeClassifier(criterion='entropy', random_state=1)
DTClassifier.fit(X,Y)
print('Accuracy of logistic decision tree classifier on test set: {:.2f}'.format(DTClassifier.score(test_data, res)))
predicted =DTClassifier.predict(test_data)
report = classification_report(res, predicted)
print(report)


Accuracy of logistic decision tree classifier on test set: 0.70
              precision    recall  f1-score   support

           0       0.79      0.76      0.77       103
           1       0.55      0.59      0.57        51

    accuracy                           0.70       154
   macro avg       0.67      0.67      0.67       154
weighted avg       0.71      0.70      0.70       154



In [755]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 


[[78 25]
 [21 30]]
0.7572815533980582
0.2987012987012987
10.316907169491211


NAIVE BAYES

In [756]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X,Y)
print('Accuracy of naive bayes classifier on test set: {:.2f}'.format(model.score(test_data, res)))
predicted =model.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of naive bayes classifier on test set: 0.82
              precision    recall  f1-score   support

           0       0.85      0.90      0.87       103
           1       0.77      0.67      0.72        51

    accuracy                           0.82       154
   macro avg       0.81      0.78      0.79       154
weighted avg       0.82      0.82      0.82       154



In [757]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 


[[93 10]
 [17 34]]
0.9029126213592233
0.17532467532467533
6.0555516794603275


SVC

In [758]:
from sklearn.svm import SVC

svcclassifier = SVC(kernel='sigmoid')
svcclassifier.fit(X,Y)
print('Accuracy of SVM classifier on test set: : {:.2f}'.format(svcclassifier.score(test_data,res)))
predicted =svcclassifier.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of SVM classifier on test set: : 0.48
              precision    recall  f1-score   support

           0       0.61      0.64      0.62       103
           1       0.18      0.16      0.17        51

    accuracy                           0.48       154
   macro avg       0.39      0.40      0.39       154
weighted avg       0.46      0.48      0.47       154



In [759]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 


[[66 37]
 [43  8]]
0.6407766990291263
0.5194805194805194
17.942413614920596


NEURAL NETWORK

In [760]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)
clf.fit(X, Y)
print('Accuracy of MLP classifier on test set: : {:.2f}'.format(clf.score(test_data,res)))
predicted =clf.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of MLP classifier on test set: : 0.70
              precision    recall  f1-score   support

           0       0.71      0.93      0.81       103
           1       0.63      0.24      0.34        51

    accuracy                           0.70       154
   macro avg       0.67      0.58      0.57       154
weighted avg       0.68      0.70      0.65       154



In [761]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 



[[96  7]
 [39 12]]
0.9320388349514563
0.2987012987012987
10.316813710051315


RANDOM FOREST

In [762]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=10)
clf = clf.fit(X, Y)
print('Accuracy of Random Forest classifier on test set: : {:.2f}'.format(clf.score(test_data,res)))
predicted =clf.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of Random Forest classifier on test set: : 0.77
              precision    recall  f1-score   support

           0       0.79      0.90      0.84       103
           1       0.72      0.51      0.60        51

    accuracy                           0.77       154
   macro avg       0.76      0.71      0.72       154
weighted avg       0.77      0.77      0.76       154



In [763]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 



[[93 10]
 [25 26]]
0.9029126213592233
0.22727272727272727
7.849773829845298


LINEAR MODEL

In [764]:
from sklearn.linear_model import SGDClassifier

clf = SGDClassifier(loss="hinge", penalty="l2", max_iter=5)
clf.fit(X, Y)
print('Accuracy of Random Forest classifier on test set: : {:.2f}'.format(clf.score(test_data,res)))
predicted =clf.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of Random Forest classifier on test set: : 0.67
              precision    recall  f1-score   support

           0       0.68      0.96      0.80       103
           1       0.50      0.08      0.14        51

    accuracy                           0.67       154
   macro avg       0.59      0.52      0.47       154
weighted avg       0.62      0.67      0.58       154



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


In [765]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 



[[99  4]
 [47  4]]
0.9611650485436893
0.33116883116883117
11.438186977468607


**LIVER** **DATASET**

---



---



In [766]:
df = pd.read_csv('LIVER_TRAIN.csv')
df.head()

Age  Gender  Total_Bilirubin  ...  Albumin  Albumin_and_Globulin_Ratio  Class
0   50       1              0.6  ...      2.6                        1.10      1
1   65       1              0.9  ...      3.0                        0.75      1
2   49       0              0.8  ...      4.3                        1.50      1
3   33       1              1.8  ...      4.0                        1.00      1
4   48       1              0.7  ...      4.0                        1.00      0

[5 rows x 11 columns]

In [767]:
test_data = pd.read_csv('LIVER_TEST.csv')
test_data.head()

Age  Gender  Total_Bilirubin  ...  Albumin  Albumin_and_Globulin_Ratio  Class
0   45       1              2.2  ...      4.0                         1.0      1
1   45       1              2.5  ...      4.0                         1.1      1
2   48       0              0.8  ...      3.9                         1.0      1
3   41       0              0.9  ...      3.8                         1.0      0
4   65       0              0.7  ...      2.9                         0.7      0

[5 rows x 11 columns]

In [768]:
df.isna().sum()/len(df)*100

Age                           0.000000
Gender                        0.000000
Total_Bilirubin               0.000000
Direct_Bilirubin              0.000000
Alkaline_Phosphotase          0.000000
Alamine_Aminotransferase      0.000000
Aspartate_Aminotransferase    0.000000
Total_Protiens                0.000000
Albumin                       0.000000
Albumin_and_Globulin_Ratio    0.643777
Class                         0.000000
dtype: float64

In [769]:
df = df.fillna(method ='bfill')
df.isna().sum()/len(df)*100

Age                           0.0
Gender                        0.0
Total_Bilirubin               0.0
Direct_Bilirubin              0.0
Alkaline_Phosphotase          0.0
Alamine_Aminotransferase      0.0
Aspartate_Aminotransferase    0.0
Total_Protiens                0.0
Albumin                       0.0
Albumin_and_Globulin_Ratio    0.0
Class                         0.0
dtype: float64

In [770]:
X = df.drop('Class',axis=1)
Y = df['Class']
res = test_data['Class']
test_data = test_data.drop('Class', axis=1)

LOGISTIC REGRESSION

In [771]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X, Y)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(test_data, res)))
predicted =logreg.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of logistic regression classifier on test set: 0.70
              precision    recall  f1-score   support

           0       0.31      0.17      0.22        29
           1       0.76      0.88      0.81        88

    accuracy                           0.70       117
   macro avg       0.54      0.52      0.52       117
weighted avg       0.65      0.70      0.67       117



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [772]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 



[[ 5 24]
 [11 77]]
0.1724137931034483
0.29914529914529914
10.332276616753832


DECISION TREE

In [773]:
from sklearn.tree import DecisionTreeClassifier
DTClassifier= DecisionTreeClassifier(criterion='entropy', random_state=1)
DTClassifier.fit(X,Y)
print('Accuracy of logistic decision tree classifier on test set: {:.2f}'.format(DTClassifier.score(test_data, res)))
predicted =DTClassifier.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of logistic decision tree classifier on test set: 0.61
              precision    recall  f1-score   support

           0       0.23      0.24      0.23        29
           1       0.74      0.73      0.74        88

    accuracy                           0.61       117
   macro avg       0.48      0.48      0.48       117
weighted avg       0.62      0.61      0.61       117



In [774]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 


[[ 7 22]
 [24 64]]
0.2413793103448276
0.39316239316239315
13.579498335977398


NAIVE BAYES

In [775]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X,Y)
print('Accuracy of naive bayes classifier on test set: {:.2f}'.format(model.score(test_data, res)))
predicted =model.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of naive bayes classifier on test set: 0.50
              precision    recall  f1-score   support

           0       0.33      1.00      0.50        29
           1       1.00      0.33      0.50        88

    accuracy                           0.50       117
   macro avg       0.66      0.66      0.50       117
weighted avg       0.83      0.50      0.50       117



In [776]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 



[[29  0]
 [59 29]]
1.0
0.5042735042735043
17.416989805980602


SVC

In [777]:
from sklearn.svm import SVC

svcclassifier = SVC(kernel='sigmoid')
svcclassifier.fit(X,Y)
print('Accuracy of SVM classifier on test set: : {:.2f}'.format(svcclassifier.score(test_data,res)))
predicted =svcclassifier.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of SVM classifier on test set: : 0.62
              precision    recall  f1-score   support

           0       0.17      0.14      0.15        29
           1       0.73      0.77      0.75        88

    accuracy                           0.62       117
   macro avg       0.45      0.46      0.45       117
weighted avg       0.59      0.62      0.60       117



In [778]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 



[[ 4 25]
 [20 68]]
0.13793103448275862
0.38461538461538464
13.284315621425089


NEURAL NETWORK

In [779]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)
clf.fit(X, Y)
print('Accuracy of MLP classifier on test set: : {:.2f}'.format(clf.score(test_data,res)))
predicted =clf.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of MLP classifier on test set: : 0.75
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        29
           1       0.75      1.00      0.86        88

    accuracy                           0.75       117
   macro avg       0.38      0.50      0.43       117
weighted avg       0.57      0.75      0.65       117



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [780]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 



[[ 0 29]
 [ 0 88]]
0.0
0.24786324786324787
8.561091485281073


RANDOM FOREST

In [781]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=10)
clf = clf.fit(X, Y)
print('Accuracy of Random Forest classifier on test set: : {:.2f}'.format(clf.score(test_data,res)))
predicted =clf.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of Random Forest classifier on test set: : 0.68
              precision    recall  f1-score   support

           0       0.40      0.55      0.46        29
           1       0.83      0.73      0.78        88

    accuracy                           0.68       117
   macro avg       0.62      0.64      0.62       117
weighted avg       0.72      0.68      0.70       117



In [782]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 



[[16 13]
 [24 64]]
0.5517241379310345
0.3162393162393162
10.9226078750281


LINEAR MODEL

In [783]:
from sklearn.linear_model import SGDClassifier

clf = SGDClassifier(loss="hinge", penalty="l2", max_iter=5)
clf.fit(X, Y)
print('Accuracy of Random Forest classifier on test set: : {:.2f}'.format(clf.score(test_data,res)))
predicted =clf.predict(test_data)
report = classification_report(res, predicted)
print(report)

Accuracy of Random Forest classifier on test set: : 0.64
              precision    recall  f1-score   support

           0       0.39      0.83      0.53        29
           1       0.91      0.58      0.71        88

    accuracy                           0.64       117
   macro avg       0.65      0.70      0.62       117
weighted avg       0.78      0.64      0.66       117



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


In [784]:
ans=confusion_matrix(res,predicted)
print(ans)
specificity= ans[0,0]/(ans[0,0]+ans[0,1])
print(specificity)
hamming_loss = metrics.hamming_loss(res, predicted)
print(hamming_loss) 
cross_entropy_loss = metrics.log_loss(res, predicted)
print(cross_entropy_loss) 


[[24  5]
 [37 51]]
0.8275862068965517
0.358974358974359
12.398569286952133
